# -*- coding: utf-8 -*-
"""Model_Predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XhZoqArdhq6811Rr0foGeKf-9rM6FZMZ
"""

import os
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
from tensorflow.keras.preprocessing import image

# Define the class labels
class_labels = [
    'Batik Cendrawasih',
    'Batik Dayak',
    'Batik Ikat Celup',
    'Batik Insang',
    'Batik Kawung',
    'Batik Megamendung',
    'Batik Parang',
    'Batik Poleng',
    'Batik Sekar Jagad',
    'Batik Tambal'
]

# Load the trained model
model = tf.keras.models.load_model('./batik_model.h5',
                                   custom_objects={'KerasLayer': hub.KerasLayer})


def predict(img):
    img = img.resize((224, 224))
    img = img.convert('RGB')
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = x / 255.0
    predictions = model.predict(x)
    predicted_class_index = np.argmax(predictions[0])
    predicted_class_label = class_labels[predicted_class_index]
    confidence = np.max(predictions[0])
    return predicted_class_label, confidence


# Path to the image want to predict
# image_path = '/content/drive/MyDrive/Capstone Project/Model_Predict/78.jpg'

# Make a prediction
# predicted_class, confidence = predict(image_path)
# print('Predicted class:', predicted_class)
# print('Confidence:', confidence)
